name: ExplosionsControl
version: '${project.version}'
main: me.itzispyder.explosionscontrol.ExplosionsControl
api-version: 1.17
authors: [ ItziSpyder ]
description: Control the explosions in your server!
website: https://github.com/ItziSpyder
commands:
  explosions:
    description: Controls and toggles explosions!
    usage: /explosions
    aliases:
      - explosions
      - ex
  explosionscontrol:
    description: About this plugin!
    usage: /explosionscontrol
    aliases:
      - explosionscontrol
      - exc
  loadworlds:
    description: Load worlds!
    usage: /loadworlds
